name: chrisanderson
favicon: null
layout_spectrum: 0.9664947267156094
typography_spectrum: 0.9318561695981771
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.04215465020388365
  lightness: 0.3713191587012261
  saturation: 0.9113869161810726
  rhythmicContrast: 0.6945942959282547
purpose: []
